Extension/README.md
Add link to contribution information to README
=> Add link to contribution information

Extension/CONTRIBUTING.md
Fix link to backend source code
=> Fix link to backend source code

Backend/README.md
Fix links to public available resources, some typos and make email proper mailto links
=> Fix links and typos

README.md
Fix links to images in README after README was moved to root directory.
=> Fix links to images in README

RetrospectiveExtension.Frontend/components/boardSummaryTable.tsx
=> 'removed' state removed from counting work items

RetrospectiveExtension.Frontend/components/actionItemDisplay.tsx
=> description field filled with feedback card content

RetrospectiveExtension.Frontend/components/feedbackBoardMetadataForm.tsx, RetrospectiveExtension.Frontend/index.tsx
=> more icons and colors added to column options

RetrospectiveExtension.Frontend/components/feedbackBoardMetadataForm.tsx, RetrospectiveExtension.Frontend/css/feedbackBoardMetadataForm.scss
=> adding template options when creating a new retrospective

RetrospectiveExtension.Frontend/utilities/boardUrlHelper.tsx
=> fix for copy retro board url

RetrospectiveExtension.Frontend/components/editableText.tsx
fixes #90 
fixes #91 
fixes #96 
fixes #103
=> on text change new text is saved to state

RetrospectiveExtension.Frontend/css/editableDocumentCardTitle.scss, RetrospectiveExtension.Frontend/css/feedbackItem.scss
Changed retro card font text colors to the primary color, to increase contrast to make it more readable
Change retro card font for the date to use theme color, to support better readability on dark theme
=> Changed font color to enhance readability

RetrospectiveExtension.Frontend/css/boardSummary.scss, RetrospectiveExtension.Frontend/css/contextualMenu.scss, RetrospectiveExtension.Frontend/css/feedbackBoardContainer.scss, RetrospectiveExtension.Frontend/css/feedbackBoardPreviewEmail.scss, RetrospectiveExtension.Frontend/css/feedbackItemGroup.scss, RetrospectiveExtension.Frontend/css/selectorCombo.scss
=> enpolat/fixing UI styles

RetrospectiveExtension.Frontend/components/__mocks__/mocked_components/mockedFeedbackColumn.tsx, RetrospectiveExtension.Frontend/components/__mocks__/uuid/v4.tsx, RetrospectiveExtension.Frontend/components/__tests__/setupTests.tsx, RetrospectiveExtension.Frontend/package-lock.json, RetrospectiveExtension.Frontend/package.json
@msa2984 fixed the tests that were breaking  during OCW. Thank you @msa2984 !!!
=> Fixes Tests

RetrospectiveExtension.Frontend/utilities/shareBoardHelper.tsx
=> Fixing Export to CSV breaking at commas

RetrospectiveExtension.Frontend/assets/PACKAGE-DESCRIPTION.md
=> Add Absolute Paths to Images

RetrospectiveExtension.Frontend/components/actionItemDisplay.tsx, RetrospectiveExtension.Frontend/css/boardSummary.scss
#386 - Catching when a user is no longer part of an organization.
=> History view error - displayName of System.AssignedTo failing

RetrospectiveExtension.Frontend/css/feedbackColumn.scss, RetrospectiveExtension.Frontend/css/feedbackItem.scss, RetrospectiveExtension.Frontend/css/feedbackItemGroup.scss
=> Adjust behavior for card tiling and other visual adjustments.

RetrospectiveExtension.Frontend/components/feedbackItem.tsx
=> Fix Grouping Not Behaving Consistently

RetrospectiveExtension.Frontend/components/feedbackBoardContainer.tsx, RetrospectiveExtension.Frontend/css/retrospectiveSummary.scss
=> improving retro summary dialog

README.md
Multiple updates to the readme file
=> Dstoddar readme

README.md
Made editorial updates as well as added a few additional images for clarifications.
=> Editorial Updates by Susan Sims

README.md
I made updates in the Team Assessment steps (7.1) and then I added a lot of content to the Best Practices section.
=> Best Practices Content

README.md
Made updates to section 7.1 to be consistent with the feedback
=> Readme-27SeptUpdates

.github/PULL_REQUEST_TEMPLATE.md
Adding some Pull Request template fields. Addresses #414 (the PR template part).
=> Creating the Pull Request Template

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md
Create the issue templates for Bugs, Feature Requests and Questions.
=> Update issue templates

CHANGELOG.md, RetrospectiveExtension.Frontend/components/extensionSettingsMenu.tsx, RetrospectiveExtension.Frontend/dal/itemDataService.tsx, RetrospectiveExtension.Frontend/package.json, RetrospectiveExtension.Frontend/vss-extension-prod.json
=> import and export data feature

RetrospectiveExtension.Frontend/components/feedbackBoardMetadataForm.tsx, RetrospectiveExtension.Frontend/utilities/boardColumnsHelper.tsx
Speedboat retro template
Speedboat retro template
=> Added Speedboat retro template

RetrospectiveExtension.Frontend/components/__tests__/feedbackCarousel.test.tsx, RetrospectiveExtension.Frontend/components/feedbackCarousel.tsx
Relevant Issue(s): #489 
This PR fixes the `feedbackCarousel` tests.
N/A
=> Fixed carousel tests from merge

.github/workflows/cd_frontend.yml
=> updating frontend cd pipeline

vsts-extension-retrospectives.sln
This pull request adds a dotnet solution file to the repository.
=> adding dotnet solution

.github/workflows/cd_frontend.yml, RetrospectiveExtension.Frontend/components/__tests__/workflowStage.test.tsx, RetrospectiveExtension.Frontend/components/feedbackBoardContainer.tsx, RetrospectiveExtension.Frontend/components/workflowStage.tsx, RetrospectiveExtension.Frontend/scripts/update_ext_manifest.sh, vsts-extension-retrospectives.sln
Fixes #590
Adding `aria-setsize` and `aria-posinset` attributes to _Retrospective Board_ tabs (`Collect`, `Group`, `Vote`, `Act`)
=> 590-required-aria-parent-role-is-not-present-for-the-tab-items-in-the-page

RetrospectiveExtension.Frontend/components/__tests__/__snapshots__/editableText.test.tsx.snap, RetrospectiveExtension.Frontend/components/editableText.tsx
=> removing unneeded aria attribute

RetrospectiveExtension.Frontend/components/__tests__/__snapshots__/editableText.test.tsx.snap, RetrospectiveExtension.Frontend/components/editableText.tsx
=> adding missing attributes to improve accessibility

RetrospectiveExtension.Frontend/css/main.scss
=> removing outline css to improve accessibility

RetrospectiveExtension.Frontend/components/feedbackBoardMetadataForm.tsx
=> adding missing aria attribute to improve accessibility

RetrospectiveExtension.Frontend/css/feedbackBoardMetadataForm.scss
=> fixing css styles to improve accessibility

RetrospectiveExtension.Frontend/components/feedbackBoardContainer.tsx, RetrospectiveExtension.Frontend/components/feedbackColumn.tsx
=> fixing header elements to improve accessibility

RetrospectiveExtension.Frontend/components/feedbackBoardMetadataForm.tsx
=> adding asterisk mark to the required fields

RetrospectiveExtension.Frontend/components/feedbackBoardContainer.tsx
=> adding required aria role to fix accessibility issue

.github/dependabot.yml
=> enabling dependabot

CHANGELOG.md
=> formatting changelog document

CODE_OF_CONDUCT.md
formatting code of conduct document
=> formatting code of conduct document

CONTRIBUTING.md
formatting contributing document
=> formatting contributing document

LICENSE
=> formatting license document

SECURITY.md
=> formatting security document

README.md
=> formatting readme document

RetrospectiveExtension.Frontend/components/feedbackBoardMetadataForm.tsx
=> fixing linter warnings

.pre-commit-config.yaml
removing unneeded pre commit hook configuration
=> removing unneeded pre commit hook configuration

RetrospectiveExtension.Frontend/components/feedbackColumn.tsx
=> fixing aria label attributes to improve accessibility

RetrospectiveExtension.Frontend/components/feedbackBoardMetadataForm.tsx
=> fixing heading levels to improve accessibility

RetrospectiveExtension.Frontend/components/feedbackBoardMetadataForm.tsx
=> adding tooltip attributes to improve accessibility

CHANGELOG.md, RetrospectiveExtension.Frontend/components/extensionSettingsMenu.tsx, RetrospectiveExtension.Frontend/vss-extension-prod.json
Relevant Issue(s): Release changes from the past several months
Release updates from over the past few months.
=> Release 1.92

RetrospectiveExtension.Frontend/dal/azureDevOpsCoreService.tsx
=> fixing infinite loop issue that causes a loading problem

RetrospectiveExtension.Frontend/components/__tests__/__snapshots__/editableText.test.tsx.snap, RetrospectiveExtension.Frontend/components/editableText.tsx
=> adding aria-required attribute to the text field

RetrospectiveExtension.Frontend/components/feedbackBoardContainer.tsx, RetrospectiveExtension.Frontend/utilities/boardUrlHelper.tsx
=> implementing push state

RetrospectiveExtension.Frontend/css/feedbackItem.scss
=> removing secondary color style from date field text

RetrospectiveExtension.Frontend/components/feedbackBoardContainer.tsx, RetrospectiveExtension.Frontend/css/feedbackBoardContainer.scss, RetrospectiveExtension.Frontend/dal/boardDataService.tsx, RetrospectiveExtension.Frontend/interfaces/feedback.tsx, RetrospectiveExtension.Frontend/utilities/telemetryClient.ts
=> creating archive button

RetrospectiveExtension.Frontend/dal/azureDevOpsWorkService.tsx, RetrospectiveExtension.Frontend/dal/boardDataService.tsx, RetrospectiveExtension.Frontend/dal/dataService.tsx, RetrospectiveExtension.Frontend/dal/itemDataService.tsx
=> fixing retrospective board rendering issue

src/frontend/components/feedbackBoardContainer.tsx
=> new api to create retrospective boards programmatically

.github/workflows/ci_cd_frontend.yml
=> removing redundant global dependencies, pinning tfx-cli dependency

src/frontend/components/extensionSettingsMenu.tsx, src/frontend/components/feedbackBoardContainer.tsx, src/frontend/scripts/update_ext_manifest.sh
Fixes #868
Fixes #757 
Fixes #731 
Fixes #537 
Fixes #509 
Fixes #499 
Fixes #350 
Fixes #333 
Fixes #245
=> switching to teams that user has permission

src/frontend/components/feedbackBoardContainer.tsx
Fixes #885 
_Version [v1.92.25](https://github.com/microsoft/vsts-extension-retrospectives/releases/tag/v1.92.25) will have the fix_
=> adding console.logs to troubleshoot

.pre-commit-config.yaml, src/frontend/components/effectivenessMeasurementRow.tsx, src/frontend/components/feedbackBoardContainer.tsx, src/frontend/dal/itemDataService.tsx
=> fixing save button on the team assessment dialog

README.md, src/frontend/package-lock.json, src/frontend/package.json
Reverting `react-toastify` update to fix #958 and fix #956
=> reverting react-toastify update

src/frontend/index.tsx
Relevant Issue(s): Regarding: #984. 
Fixes #984 
Fixes #1001 
CDN used for the fonts became deprecated. Updated to new one. 
document.
=> icons-missing-fix #984

src/frontend/components/feedbackBoard.tsx, src/frontend/components/feedbackItem.tsx
=> fixing voting

src/frontend/assets/PACKAGE-DESCRIPTION.md
Relevant Issue(s): #1032 
Fixes broken links.
- [ x] Bug fix
- [ x] I have read the [**CONTRIBUTING**](https://github.com/microsoft/vsts-extension-retrospectives/blob/main/CONTRIBUTING.md)
document.
- [ n/a] My code follows the code style of this project.
- [n/a] I have updated any relevant documentation accordingly.
- [n/a ] I have included an update blurb (50 words or less) at the top of `CHANGELOG.md`,
- [ n/a] I have included a link to this PR in that blurb.
- [n/a ] I have added tests to cover my changes.
- [ n/a] All new and existing tests passed.
=> Fixed image refs #1032

src/frontend/components/feedbackBoardMetadataForm.tsx, src/frontend/utilities/effectivenessMeasurementQuestionHelper.tsx
Relevant Issue(s): no issue logged
Removes a couple words to reduce line wrap for Team Assessment, so line wrap limited to two lines.
=> Reduce wording to remove runts.

CONTRIBUTING.md, src/backend/ReflectHub.cs, src/frontend/components/__tests__/feedbackBoardMetadataForm.test.tsx, src/frontend/components/boardSummaryTable.tsx, src/frontend/components/feedbackBoardContainer.tsx, src/frontend/components/feedbackBoardMetadataForm.tsx, src/frontend/dal/boardDataService.tsx, src/frontend/dal/reflectBackendService.tsx
Relevant Issue(s): #1084
Enable and restore archive from History tab.
Coincidentally corrected camelCase for maxvotesPerUser to maxVotesPerUser.
=> Enable Archive and Restore from History Tab

CHANGELOG.md, src/frontend/components/extensionSettingsMenu.tsx
Relevant Issue(s): #1121 
updating changelog and what's new for template release
=> updated change log and what's new for template release

.github/workflows/ci_backend.yml, src/backend.tests/packages.lock.json, src/backend/packages.lock.json
Fixes https://github.com/microsoft/vsts-extension-retrospectives/security/code-scanning/65
=> pinning nuget packages to improve security on restoring dependencies and addressing code scanning alert on github security

src/frontend/package-lock.json, src/frontend/package.json
Fixes https://github.com/microsoft/vsts-extension-retrospectives/security/code-scanning/38
=> chore: add package overrides for cross-spawn, execa, and clipboardy

src/frontend/components/feedbackColumn.tsx
=> update aria-label to include feedback item count in FeedbackColumn

src/frontend/components/__tests__/feedbackBoardMetadataForm.test.tsx
Relevant Issue(s): NA
Improves test code coverage for feedbackBoardMetadataForm.
=> Test issue 1283
