microsoft/vsts-extension-retrospectives

Extension/src/Retrospective.Hub.Extension/components/feedbackBoard.tsx
Extension/src/Retrospective.Hub.Extension/components/feedbackBoardContainer.tsx
Extension/src/Retrospective.Hub.Extension/components/feedbackBoardMetadataForm.tsx
Extension/src/Retrospective.Hub.Extension/components/feedbackColumn.tsx
Extension/src/Retrospective.Hub.Extension/components/feedbackItem.tsx
Extension/src/Retrospective.Hub.Extension/css/feedbackItem.scss
Extension/src/Retrospective.Hub.Extension/dal/boardDataService.tsx
Extension/src/Retrospective.Hub.Extension/dal/itemDataService.tsx
Extension/src/Retrospective.Hub.Extension/interfaces/feedback.tsx
Extension/src/Retrospective.Hub.Extension/vss-extension-dev.json

Fixes #4 
This PR adds an extra option during the creation of a retrospective to only show the cards of the other participants after the "Collect" phase. When switching to "Group", "Vote" or "Act" the feedback items are shown. I chose this approach for now as a first improvement and did not yet add a button as discussed in the issue. This can be added/improved later on.
**Remarks:**
- I could not test this with live syncing as I get the following message: `We are unable to connect to the live syncing service. You can continue to create and edit items as usual, but changes will not be updated in real-time to or from other users`. It seems this has something to do with CORS settings on the backend service and I'm not sure how to resolve this.
- Changed the category from "Plan and track" to …

Add option to hide cards during Collect phase

---

RetrospectiveExtension.Frontend/vss-extension-dev.json
RetrospectiveExtension.Frontend/vss-extension-prod.json

Add link to repository to extension metadata to improve discoverability of source code.
By default Q & A section would redirect to GitHub issues if a GitHub repository link is available. Since there's already an existing Q & A section I disabled this feature to keep the existing entries.

Add link to repository to extension metadata

---

RetrospectiveExtension.Frontend/components/feedbackItem.tsx
RetrospectiveExtension.Frontend/dal/itemDataService.tsx

With this feature, users can now decrement a vote on a specific item. Users might have clicked by mistake or they might change their mind to vote on another item instead. Previously there was no way to decrement/remove a vote once added. This now adds a unvote (down arrow) button to an item to let users unvote.

unvote feature

---

RetrospectiveExtension.Frontend/components/feedbackColumn.tsx
RetrospectiveExtension.Frontend/components/feedbackItem.tsx
RetrospectiveExtension.Frontend/dal/itemDataService.tsx
RetrospectiveExtension.Frontend/interfaces/feedback.tsx

With the initial unvote feature, Engin had pointed out that:
>with this implementation, people can uncast votes that they didn’t cast, so, they can drain already casted votes from other people
These changes should take care of that.

restrict unvote to only your votes

---

RetrospectiveExtension.Frontend/components/feedbackBoard.tsx
RetrospectiveExtension.Frontend/components/feedbackBoardContainer.tsx
RetrospectiveExtension.Frontend/components/feedbackBoardMetadataForm.tsx
RetrospectiveExtension.Frontend/components/feedbackItem.tsx
RetrospectiveExtension.Frontend/dal/boardDataService.tsx
RetrospectiveExtension.Frontend/dal/itemDataService.tsx
RetrospectiveExtension.Frontend/interfaces/feedback.tsx

Retrospective creator can now set the max vote limit for each user. 
This limit can be changed using the 'Edit Retrospective' dialog but note that the current votes exceeding the new limit will stay on - so use update with caution. This change should ideally be used before voting begins when team collectively thinks that the limit should be different from originally set.

Max Votes per User Feature

---

RetrospectiveExtension.Frontend/dal/itemDataService.tsx

I have removed the broadcast that was needed and possibly is the cause of the issues we are seeing during the voting process (boards flipping to collect phase)

remove unneeded broadcast that's causing issues

---

RetrospectiveExtension.Frontend/dal/itemDataService.tsx

Conditional init of the VoteCollection was occurring every time when a user was voting for the first time on the board thus resetting votes of other users who had already voted.
Reconfigured the conditional blocks

correct conditional init of voteCollection during vote

---

RetrospectiveExtension.Frontend/components/feedbackItem.tsx

The retro board is often shared on a screen by the moderator when in `Act` mode. Since the moderator can also vote, we don't want to show the `yourvote-count` when in `Act` mode.
This PR changes the visibility of the `yourvote-count` div based on the mode, i.e. only show in `Vote` mode.

Don't show yourvote-count in Act mode

---

RetrospectiveExtension.Frontend/components/feedbackItem.tsx

When an item card does **not** have the timer running, the icon is the
triangular play button, inside of a circle. When the timer is started,
the button's icon is the square "stop" button. However, this is not
contained within a circle. This looks strange by comparison, and looks
like a bug (as it's just a solid-colored box).
Fix this by using the `fa-stop-circle` icon, which matches the existing
`fa-play-circle` button.
Here's what it looks like before this fix:
And here's what it looks like after this fix:

fix: Use the matching "stop" icon for an item card

---

CONTRIBUTING.md

Update `README` to reflect the video you posted. `build:p` does not exist in `packages.json`.
Signed-off-by: arabah <83525683+arabah@users.noreply.github.com>

Simple fix to a readme file

---

RetrospectiveExtension.Frontend/utilities/boardUrlHelper.tsx

The board URL can contain spaces (the project name is allowed to have
spaces), which results in broken links because the spaces aren't
encoded.
By routing the URL through `encodeURI(..)`, the resulting URL is safe
for consumption by external systems.

fix: Encode the board URL

---

RetrospectiveExtension.Frontend/components/__mocks__/mocked_components/mockedFeedbackColumn.tsx
RetrospectiveExtension.Frontend/components/feedbackBoardContainer.tsx
RetrospectiveExtension.Frontend/components/feedbackBoardMetadataForm.tsx
RetrospectiveExtension.Frontend/components/feedbackColumn.tsx
RetrospectiveExtension.Frontend/components/feedbackItem.tsx
RetrospectiveExtension.Frontend/dal/boardDataService.tsx
RetrospectiveExtension.Frontend/interfaces/feedback.tsx

As to not break any old boards, now you have to opt into keeping grouping within columns. You're still able to see the original column something written into when it moves across columns, grouped or not!

Swap the grouping logic so you have to opt out of moving across columns.

---

README.md
RetrospectiveExtension.Frontend/components/feedbackBoardMetadataForm.tsx

#410 - Renames the `Make all feedback anonymous` option to `Do not display names in feedback`

Update strings and README for anonymous feedback

---

RetrospectiveExtension.Frontend/css/feedbackItemGroup.scss

Link of issue: https://github.com/microsoft/vsts-extension-retrospectives/issues/420
Basically on card-integral-part are missing the global variable of Azure DevOps theme background.

fix: Grouped Items are Unreadable in Dark Mode #420

---

.github/workflows/cd_frontend.yml
.github/workflows/ci_backend.yml
.github/workflows/ci_frontend.yml

Fixes #435. There was a branch renaming, so things are on `main`. Now the GH actions reflect that!

Re-enabling the CI/CD GH Actions

---

.github/workflows/ci_frontend.yml
RetrospectiveExtension.Frontend/components/__tests__/feedbackItem.test.tsx
RetrospectiveExtension.Frontend/components/boardSummary.tsx
RetrospectiveExtension.Frontend/components/extensionSettingsMenu.tsx
RetrospectiveExtension.Frontend/components/feedbackBoardContainer.tsx
RetrospectiveExtension.Frontend/components/feedbackItem.tsx
RetrospectiveExtension.Frontend/components/selectorCombo.tsx
RetrospectiveExtension.Frontend/package-lock.json
RetrospectiveExtension.Frontend/package.json

Fixes #438 for front end CI problems.

Fix the CI Errors Found in the GH Action

---

RetrospectiveExtension.Frontend/components/feedbackBoardContainer.tsx

The menu iconography was changed in #422 from `...` to `:::`.
However, `:::` is generally used for a drag handle in a drag-and-drop
UI, rather than an overflow menu.

fix: Restore "..." for menu button

---

CHANGELOG.md
RetrospectiveExtension.Frontend/components/feedbackBoardMetadataForm.tsx
RetrospectiveExtension.Frontend/utilities/boardColumnsHelper.tsx

Relevant Issue(s): N/A
Unifying board template column helpers
N/A

unifying-board-template-column-helper

---

RetrospectiveExtension.Backend/deploy/env_setup.sh

#486 
Change deploy script references from .NET 5 to .NET 6.

Change deploy script references from .NET 5 to .NET 6

---

CHANGELOG.md
RetrospectiveExtension.Frontend/components/feedbackBoardContainer.tsx
RetrospectiveExtension.Frontend/css/feedbackBoardContainer.scss

Relevant Issue(s): #466 
This PR aligns the colors in the Team Assessment Form to be similar to the three categories in the summary (Unfavorable, Neutral, Favorable).
Light Theme:
Dark Theme:

#466: Team Assessment Form Color Gradient to Match Summary

---

RetrospectiveExtension.Frontend/utilities/effectivenessMeasurementQuestionHelper.tsx

This pull request addresses minor grammatical and parallelism issues with a retrospective assessment question by aligning it with the parallel verbiage from Microsoft's "Thriving" bank of questions.
Specific issues:
- 'Energy' inconsistently refers to "this past sprint" when all other questions ask in a period-independent context; the latter is generally preferred for appropriate flexibility in responses
- The use of 'everyday' instead of the phrase 'every day' is an English grammatical error; see resources like this one for more information: https://www.grammarly.com/blog/everyday-every-day/

VSTS retro assessment resources: minor update to 'energy' question

---

RetrospectiveExtension.Frontend/css/feedbackBoardMetadataForm.scss

When creating new retrospective hub, checkbox do not have a visual effect
Relevant Issue(s): #526 
Removing display where ms-Checkbox is checked
Hover when false:
Hover when true:

When creating new retrospective hub, checkbox do not have a visual effect #526

---

RetrospectiveExtension.Frontend/components/feedbackItem.tsx
RetrospectiveExtension.Frontend/css/feedbackItem.scss

adding label for the subtext of the dialog

---

RetrospectiveExtension.Frontend/components/boardSummaryTable.tsx

fixing screen readers (NVDA/JAWS) behaviors not narrating role and sorting information for the column headers

---

RetrospectiveExtension.Frontend/components/feedbackItem.tsx

fixing in 200% zoom mode, Content which is present in the dialog is not visible

---

CHANGELOG.md
RetrospectiveExtension.Frontend/components/__tests__/feedbackItem.test.tsx
RetrospectiveExtension.Frontend/components/feedbackItem.tsx

Relevant Issue(s): Fixes #521 
Changes the visual numbering on the cards to start at 1
document.

Start Card Numbering at 1

---

RetrospectiveExtension.Frontend/components/__tests__/feedbackBoardMetadataFormPermissions.test.tsx
RetrospectiveExtension.Frontend/components/feedbackBoardMetadataForm.tsx
RetrospectiveExtension.Frontend/components/feedbackBoardMetadataFormPermissions.tsx
RetrospectiveExtension.Frontend/css/feedbackBoardMetadataFormPermissions.scss

Relevant Issue(s): #650 
Improved the UI for board permissions to display the current board owner to help reduce confusion on why users can still see a board. Owners/Creators of boards cannot be removed.
document.

Board permission owner label 

---

RetrospectiveExtension.Frontend/components/feedbackBoardContainer.tsx
RetrospectiveExtension.Frontend/css/feedbackBoardMetadataFormPermissions.scss

Relevant Issue(s): #671 
Fixed a loading issue that can occur from a race condition with the current state. This ensures we're are trying to load the most recent team and board without relying on the state to be updated for the initial load. Also fixed the image sizing on board permissions.
document.
N/A

Fixed loading issue for boards

---

src/frontend/components/feedbackColumn.tsx

Relevant Issue(s): #520 and #1045
Orders cards by created date, except if Act column, then orders by votes, then modified date
- [ x] New feature

Orders cards by created date, unless Act column, then orders by votes

---

src/frontend/components/feedbackBoardContainer.tsx

Relevant Issue(s): #515 and #682
Replaces undefined session date which defaults to current date with created date for the retrospective summary.  Created date and created by will be displayed instead of current date and created by.

Replaces undefined Session Date with Created Date

---

src/frontend/components/actionItemDisplay.tsx

Relevant Issue(s): #540
Removes redundant "reflect-hub" tag when adding a work item from a retrospective card.  There are two tags: "feedback" and "reflect-hub".  Better to choose just one tag.  The "feedback" tag is more easily interpreted by the user community, than  "reflect-hub" which is a reference to the original development name of the Retrospective extension.

Removes redundant reflect-hub tag when adding work item

---

README.md
src/frontend/components/feedbackBoardContainer.tsx

Relevant Issue(s): #1038, #998, #935, #929, #914, #793
Removed All Teams
Retrospectives should be safe space for team members to share feedback.
Therefore, should not have access to other teams' retrospective boards.
Currently the code sets All Teams to the equivalent of My Teams.
Better to not leave false impression that displaying All Teams.

Remove All Teams

---

src/frontend/components/__tests__/feedbackBoardMetadataFormPermissions.test.tsx
src/frontend/components/feedbackBoardContainer.tsx
src/frontend/components/feedbackBoardMetadataForm.tsx
src/frontend/components/feedbackBoardMetadataFormPermissions.tsx

Relevant Issue(s): #983 
Starts over with clean fix for blank and duplicate permissions.  Blank permissions was introduced when removed All Teams.  Some code was being used to find all the teams the user was a member of.  That code was restored.  Duplicates occurred when the user was a member of more than one team.  The code added all the members for each team, regardless if they were duplicates.  The code now removes the duplicates.
Also changes the sort order to:
1) Owner 
2) Teams with permission sorted alphabetically
3) Users with permission sorted alphabetically
4) Teams without permission sorted alphabetically
5) Users without permission sorted alphabetically
Known bug: When creating a new board, the permission will show the owner for the current board, not the board creator, until …

Start over with clean fix for blank and duplicate permissions

---

src/frontend/css/contextualMenu.scss

Fixes bug that causes user settings menu to auto scroll back to top
Relevant Issue(s): #1136 
Fix issue #1136 
document.

User Settings Menu bug fix

---

src/frontend/package-lock.json
src/frontend/package.json

Updating `npm run clean` command to run correctly on Windows and overall build of the frontend extension
Updating `npm run clean` command to run correctly on Windows and overall build of the frontend extension:
`"clean": "npx rimraf ./dist ./coverage ./reports && npx del-cli ./node_modules/applicationinsights-js/dist/*.map",`
Follow dev dependency has been added:
`npm install del-cli --save-dev`
document.
to be included with the next release. N/A
N/A all

Updating NPM Clean Cmd to Build Correctly on Windows

---

package-lock.json
src/frontend/package-lock.json
src/frontend/package.json

Relevant Issue(s): #1276
Revert azure-devops-extension-api to prior version to be compatible with on-prem version.

Revert azure-devops-extension-api to prior version

---

src/frontend/components/__tests__/feedbackBoardMetadataForm.test.tsx
src/frontend/components/feedbackBoardMetadataForm.tsx

Relevant Issue(s): #1283
When user marks column for deletion and clicks save, a confirmation dialog box opens and no action occurs when clicking Confirm.

Correct handling after confirming okay to delete column

---

CHANGELOG.md
src/frontend/components/__tests__/feedbackBoardMetadataFormPermissions.test.tsx
src/frontend/components/feedbackBoardMetadataFormPermissions.tsx

Relevant Issue(s): #1295
Identify groups by pattern and remove them from permissions, since they were not functional.

identify groups by pattern and remove them from permissions
